export interface AccountItem {
  name: string
  accountNumber: string
  rootType: 'Asset' | 'Liability' | 'Equity' | 'Income' | 'Expense'
  accountType: string
  isGroup: boolean
  parentAccount?: string
}

export const DEFAULT_IFRS_ACCOUNTS: AccountItem[] = [
  // Assets
  { name: 'Debtors', accountNumber: '1111', rootType: 'Asset', accountType: 'Receivable', isGroup: false },
  { name: 'Staff Receivable', accountNumber: '1112', rootType: 'Asset', accountType: 'Receivable', isGroup: false },
  { name: 'Allowance for Uncollectible Accounts', accountNumber: '1113', rootType: 'Asset', accountType: 'Receivable', isGroup: false },
  { name: 'Cash', accountNumber: '1121', rootType: 'Asset', accountType: 'Cash', isGroup: false },
  { name: 'Petty Cash', accountNumber: '1122', rootType: 'Asset', accountType: 'Cash', isGroup: false },
  { name: 'Bank', accountNumber: '1131', rootType: 'Asset', accountType: 'Bank', isGroup: false },
  { name: 'Fixed Deposits', accountNumber: '1132', rootType: 'Asset', accountType: 'Bank', isGroup: false },
  { name: 'Stock in Hand', accountNumber: '1141', rootType: 'Asset', accountType: 'Stock', isGroup: false },
  { name: 'Raw Materials', accountNumber: '1142', rootType: 'Asset', accountType: 'Stock', isGroup: false },
  { name: 'Work in Progress', accountNumber: '1143', rootType: 'Asset', accountType: 'Stock', isGroup: false },
  { name: 'Finished Goods', accountNumber: '1144', rootType: 'Asset', accountType: 'Stock', isGroup: false },
  { name: 'Goods in Transit', accountNumber: '1145', rootType: 'Asset', accountType: 'Stock', isGroup: false },
  { name: 'Input Tax Credit', accountNumber: '1151', rootType: 'Asset', accountType: 'Tax', isGroup: false },
  { name: 'Advance Tax Paid', accountNumber: '1152', rootType: 'Asset', accountType: 'Tax', isGroup: false },
  { name: 'VAT Receivable', accountNumber: '1153', rootType: 'Asset', accountType: 'Tax', isGroup: false },
  { name: 'Prepaid Rent', accountNumber: '1156', rootType: 'Asset', accountType: 'Prepayment', isGroup: false },
  { name: 'Prepaid Insurance', accountNumber: '1157', rootType: 'Asset', accountType: 'Prepayment', isGroup: false },
  { name: 'Accrued Interest Receivable', accountNumber: '1158', rootType: 'Asset', accountType: 'Prepayment', isGroup: false },
  { name: 'Advances to Suppliers', accountNumber: '1161', rootType: 'Asset', accountType: 'Receivable', isGroup: false },
  { name: 'Advances to Employees', accountNumber: '1162', rootType: 'Asset', accountType: 'Receivable', isGroup: false },
  { name: 'Earnest Money', accountNumber: '1171', rootType: 'Asset', accountType: '', isGroup: false },
  { name: 'Land', accountNumber: '1201', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Buildings', accountNumber: '1202', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Plant and Machinery', accountNumber: '1203', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Furniture and Fixtures', accountNumber: '1204', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Office Equipment', accountNumber: '1205', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Electronic Equipment', accountNumber: '1206', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Vehicles', accountNumber: '1207', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Capital Work in Progress', accountNumber: '1208', rootType: 'Asset', accountType: 'Fixed Asset', isGroup: false },
  { name: 'Accumulated Depreciation', accountNumber: '1210', rootType: 'Asset', accountType: 'Accumulated Depreciation', isGroup: false },
  { name: 'Software', accountNumber: '1251', rootType: 'Asset', accountType: 'Intangible Asset', isGroup: false },
  { name: 'Patents and Trademarks', accountNumber: '1252', rootType: 'Asset', accountType: 'Intangible Asset', isGroup: false },
  { name: 'Goodwill', accountNumber: '1253', rootType: 'Asset', accountType: 'Intangible Asset', isGroup: false },
  { name: 'Accumulated Amortization', accountNumber: '1254', rootType: 'Asset', accountType: 'Accumulated Amortization', isGroup: false },
  { name: 'Investments in Shares', accountNumber: '1301', rootType: 'Asset', accountType: '', isGroup: false },
  { name: 'Investments in Bonds', accountNumber: '1302', rootType: 'Asset', accountType: '', isGroup: false },
  { name: 'Investment Property', accountNumber: '1303', rootType: 'Asset', accountType: '', isGroup: false },
  { name: 'Deferred Tax Assets', accountNumber: '1350', rootType: 'Asset', accountType: 'Deferred Tax', isGroup: false },
  { name: 'Temporary Opening', accountNumber: '1901', rootType: 'Asset', accountType: 'Temporary', isGroup: false },

  // Liabilities
  { name: 'Creditors', accountNumber: '2111', rootType: 'Liability', accountType: 'Payable', isGroup: false },
  { name: 'Payroll Payable', accountNumber: '2112', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Accrued Salaries and Wages', accountNumber: '2113', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Stock Received But Not Billed', accountNumber: '2121', rootType: 'Liability', accountType: 'Stock Received But Not Billed', isGroup: false },
  { name: 'Output Tax Payable', accountNumber: '2131', rootType: 'Liability', accountType: 'Tax', isGroup: false },
  { name: 'Sales Tax Payable', accountNumber: '2132', rootType: 'Liability', accountType: 'Tax', isGroup: false },
  { name: 'Income Tax Payable', accountNumber: '2133', rootType: 'Liability', accountType: 'Tax', isGroup: false },
  { name: 'Tax Withheld at Source', accountNumber: '2134', rootType: 'Liability', accountType: 'Tax', isGroup: false },
  { name: 'VAT Payable', accountNumber: '2135', rootType: 'Liability', accountType: 'Tax', isGroup: false },
  { name: 'Secured Loans', accountNumber: '2141', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Unsecured Loans', accountNumber: '2142', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Bank Overdraft Account', accountNumber: '2143', rootType: 'Liability', accountType: 'Bank', isGroup: false },
  { name: 'Short-term Bank Loans', accountNumber: '2144', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Interest Payable', accountNumber: '2151', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Accrued Expenses', accountNumber: '2152', rootType: 'Liability', accountType: 'Provision', isGroup: false },
  { name: 'Advances from Customers', accountNumber: '2153', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Unearned Revenue', accountNumber: '2154', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Dividends Payable', accountNumber: '2155', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Current Portion of Long-term Debt', accountNumber: '2156', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Long-term Loans', accountNumber: '2201', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Bonds and Debentures Payable', accountNumber: '2202', rootType: 'Liability', accountType: '', isGroup: false },
  { name: 'Lease Liabilities', accountNumber: '2203', rootType: 'Liability', accountType: 'Lease Liability', isGroup: false },
  { name: 'Deferred Tax Liabilities', accountNumber: '2204', rootType: 'Liability', accountType: 'Deferred Tax', isGroup: false },
  { name: 'Pension & Post-Employment Obligations', accountNumber: '2205', rootType: 'Liability', accountType: 'Provision', isGroup: false },

  // Equity
  { name: 'Share Capital', accountNumber: '3101', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Share Premium', accountNumber: '3102', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Owner\'s Capital', accountNumber: '3103', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Owner\'s Drawings', accountNumber: '3104', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Retained Earnings', accountNumber: '3201', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Revaluation Reserve', accountNumber: '3202', rootType: 'Equity', accountType: 'Reserve', isGroup: false },
  { name: 'General Reserve', accountNumber: '3203', rootType: 'Equity', accountType: 'Reserve', isGroup: false },
  { name: 'Opening Balance Equity', accountNumber: '3300', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Dividends Paid', accountNumber: '3400', rootType: 'Equity', accountType: 'Equity', isGroup: false },
  { name: 'Round Off', accountNumber: '3900', rootType: 'Equity', accountType: 'Round Off', isGroup: false },

  // Income
  { name: 'Sales', accountNumber: '4101', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Service', accountNumber: '4102', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Product Sales', accountNumber: '4103', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Export Sales', accountNumber: '4104', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Fee Income', accountNumber: '4105', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Interest Income', accountNumber: '4201', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Discount Received', accountNumber: '4202', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Exchange Gain', accountNumber: '4203', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Gain on Asset Disposal', accountNumber: '4204', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Other Income', accountNumber: '4205', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Commission Received', accountNumber: '4206', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Rental Income', accountNumber: '4207', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Royalty Income', accountNumber: '4208', rootType: 'Income', accountType: 'Income Account', isGroup: false },
  { name: 'Dividend Income', accountNumber: '4209', rootType: 'Income', accountType: 'Income Account', isGroup: false },

  // Expenses
  { name: 'Cost of Goods Sold', accountNumber: '5111', rootType: 'Expense', accountType: 'Cost of Goods Sold', isGroup: false },
  { name: 'Expenses Included In Valuation', accountNumber: '5112', rootType: 'Expense', accountType: 'Expenses Included In Valuation', isGroup: false },
  { name: 'Stock Adjustment', accountNumber: '5113', rootType: 'Expense', accountType: 'Stock Adjustment', isGroup: false },
  { name: 'Direct Labour', accountNumber: '5114', rootType: 'Expense', accountType: 'Manufacturing Expense', isGroup: false },
  { name: 'Direct Material', accountNumber: '5115', rootType: 'Expense', accountType: 'Manufacturing Expense', isGroup: false },
  { name: 'Freight and Carriage Inwards', accountNumber: '5116', rootType: 'Expense', accountType: 'Cost of Goods Sold', isGroup: false },
  { name: 'Manufacturing Overheads', accountNumber: '5117', rootType: 'Expense', accountType: 'Manufacturing Expense', isGroup: false },
  { name: 'Salary and Wages', accountNumber: '5201', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Employee Benefits and Welfare', accountNumber: '5202', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Office Rent', accountNumber: '5203', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Utility Expenses', accountNumber: '5204', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Telephone Expenses', accountNumber: '5205', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Internet Expenses', accountNumber: '5206', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Travel Expenses', accountNumber: '5207', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Office Maintenance Expenses', accountNumber: '5208', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Print and Stationery', accountNumber: '5209', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Postal Expenses', accountNumber: '5210', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Legal Expenses', accountNumber: '5211', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Marketing Expenses', accountNumber: '5212', rootType: 'Expense', accountType: 'Chargeable', isGroup: false },
  { name: 'Advertising Expenses', accountNumber: '5213', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Administrative Expenses', accountNumber: '5214', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Depreciation', accountNumber: '5215', rootType: 'Expense', accountType: 'Depreciation', isGroup: false },
  { name: 'Amortization Expense', accountNumber: '5216', rootType: 'Expense', accountType: 'Depreciation', isGroup: false },
  { name: 'Entertainment Expenses', accountNumber: '5217', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Commission on Sales', accountNumber: '5218', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Freight and Forwarding', accountNumber: '5219', rootType: 'Expense', accountType: 'Chargeable', isGroup: false },
  { name: 'Miscellaneous Expenses', accountNumber: '5220', rootType: 'Expense', accountType: 'Chargeable', isGroup: false },
  { name: 'Discount Allowed', accountNumber: '5221', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Bank Charges', accountNumber: '5222', rootType: 'Expense', accountType: 'Finance Cost', isGroup: false },
  { name: 'Interest Expense', accountNumber: '5223', rootType: 'Expense', accountType: 'Finance Cost', isGroup: false },
  { name: 'Insurance Expenses', accountNumber: '5224', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Repairs and Maintenance', accountNumber: '5225', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Audit Fees', accountNumber: '5226', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Consultancy Fees', accountNumber: '5227', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Software Subscriptions', accountNumber: '5228', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Exchange Gain/Loss', accountNumber: '5229', rootType: 'Expense', accountType: 'Finance Cost', isGroup: false },
  { name: 'Gain/Loss on Asset Disposal', accountNumber: '5230', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Write Off', accountNumber: '5231', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Sales Expenses', accountNumber: '5232', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
  { name: 'Bad Debts', accountNumber: '5233', rootType: 'Expense', accountType: 'Expense Account', isGroup: false },
]
